name: 05 Execution Flow
on:
  workflow_dispatch:
    inputs:
      pass-unit-test:
        type: boolean
        description: weather unit will pass or not
        default: true
jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
      - name: Lint and build
        run: echo "Linting and building project"

  unit-test:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Run Unit Test
        run: echo "Running unit test ......"
      - name: Failing Unit Test
        if: ${{ !inputs.pass-unit-test }}
        run: exit 1
  deploy-nonprod:
    runs-on: ubuntu-latest
    needs:
      - lint-build
      - unit-test
    steps:
      - name: deploying to non prod
        run: echo "deploying to non prod"
  e2e-test:
    runs-on: ubuntu-latest
    needs:
      - deploy-nonprod
    steps:
      - name: running e2e test
        run: echo "running e2e test......."
  load-test:
    runs-on: ubuntu-latest
    needs:
      - deploy-nonprod
    steps:
      - name: running load test
        run: echo "running load test......."
  deploy-prod:
    runs-on: ubuntu-latest
    needs:
      - e2e-test
      - load-test
    steps:
      - name: deploying to  prod
        run: echo "deploying to  prod....."
